In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

In [4]:
obj = Series([4,7,5,3])

In [5]:
obj

0    4
1    7
2    5
3    3
dtype: int64

In [6]:
obj.array

<NumpyExtensionArray>
[4, 7, 5, 3]
Length: 4, dtype: int64

In [8]:
obj2 = Series([4,7,5,3], index = ["d", "b", "a", "c"])

In [9]:
obj2

d    4
b    7
a    5
c    3
dtype: int64

In [10]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
obj2["a"]

np.int64(5)

In [14]:
obj2 > 0

d    True
b    True
a    True
c    True
dtype: bool

In [15]:
sdata = {"Ohio" : 35000, "Texas" : 71000, "Oregon" : 16000, "Utah" : 5000}

In [16]:
obj3 = Series(sdata)

In [17]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [18]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [22]:
obj4 = Series(sdata, index = states)

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj4.notna()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
obj4.name = "population"

In [29]:
obj4.index.name = "state"

In [30]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
obj

0    4
1    7
2    5
3    3
dtype: int64

In [32]:
obj[2] = -5

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [5]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [6]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [7]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [9]:
DataFrame(data, columns=["year","state","pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [10]:
frame.loc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [11]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

NameError: name 'frame3' is not defined

In [12]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [13]:
frame2 = DataFrame(populations)

In [14]:
frame2

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [15]:
frame3.T

NameError: name 'frame3' is not defined

In [16]:
frame2.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [17]:
DataFrame(populations, index=[2001,2002,2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [18]:
frame1.to_numpy()

NameError: name 'frame1' is not defined

In [19]:
frame.to_numpy()

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

In [20]:
frame2.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [22]:
obj = Series(np.arange(3), index=["a", "b", "c"])

In [23]:
index = obj.index

In [24]:
index

Index(['a', 'b', 'c'], dtype='object')

In [25]:
index[1:]

Index(['b', 'c'], dtype='object')

In [26]:
labels = pd.Index(np.arange(3))

In [27]:
labels

Index([0, 1, 2], dtype='int64')

In [29]:
obj2 = Series([1.5, -2.5, 0], index = labels)

In [30]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [31]:
obj.index is labels

False

In [32]:
obj2.index is labels

True

In [33]:
frame3

NameError: name 'frame3' is not defined

In [34]:
frame2

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [37]:
frame2.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [36]:
frame2.columns.name = "state"

In [38]:
"Ohio" in frame2.columns

True

In [39]:
frame2.index

Index([2000, 2001, 2002], dtype='int64')

In [42]:
pd.Index(["foo","foo","bar","bar"])

TypeError: 'list' object is not callable

In [43]:
list = np.arange(3)

In [44]:
list

array([0, 1, 2])

In [45]:
pd.Index([0,1,2])

TypeError: 'list' object is not callable

In [46]:
pd.Index(np.array([0,1,2]))

TypeError: 'list' object is not callable

In [48]:
np.array([0,1,2])

array([0, 1, 2])

In [49]:
idx = pd.Index(list)

TypeError: 'list' object is not callable

In [50]:
del list

In [51]:
arr = np.arange(3)

In [52]:
arr

array([0, 1, 2])

In [53]:
idx = pd.Index(arr)

TypeError: 'list' object is not callable

In [54]:
print(type(list))

<class 'type'>

In [60]:
print(type(pd.Index)) 
# 만약 결과가 <class 'list'> 라면, pd.Index가 변수로 오염된 것입니다.
# 정상이라면 <class 'type'> (또는 pandas 내부 클래스명)이 떠야 합니다.

<class 'list'>

In [5]:
labels = pd.Index(["foo", "foo", "bar", "bar"])

In [6]:
labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [11]:
labels = labels.append(labels2)

In [8]:
labels2 = pd.Index(["tic", "tic"])

In [10]:
labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [12]:
labels

Index(['foo', 'foo', 'bar', 'bar', 'tic', 'tic'], dtype='object')

In [13]:
labels.difference(labels2)

Index(['bar', 'foo'], dtype='object')

In [14]:
labels.unique()

Index(['foo', 'bar', 'tic'], dtype='object')

In [4]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [5]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [6]:
obj2 = obj.reindex(["a","b","c","d","e"])

In [7]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [8]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [9]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [10]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [11]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])

In [12]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [13]:
frame2 = frame.reindex(["a","b","c","d"])

In [14]:
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [15]:
states = ["Texas", "Utah", "California"]

In [16]:
frame2.reindex(columns=states)

   Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [17]:
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [20]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [21]:
frame.loc[["a","d","c"], ["California","Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

In [22]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [23]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [24]:
new_obj = obj.drop("c")

In [25]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [26]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
data.drop(index=["Ohio","New York"])

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [29]:
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [30]:
data.drop("two",axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [31]:
data.drop(["two","four"], axis = "columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [33]:
obj = Series(np.arange(4), index = ["a","b","c","d"])

In [35]:
obj

a    0
b    1
c    2
d    3
dtype: int64

In [34]:
obj["b"]

np.int64(1)

In [36]:
obj[["a","d","c"]]

a    0
d    3
c    2
dtype: int64

In [37]:
obj[obj > 1]

c    2
d    3
dtype: int64

In [38]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj1
obj2

a    1
b    2
c    3
dtype: int64

In [40]:
obj1

2    1
0    2
1    3
dtype: int64

In [41]:
obj2

a    1
b    2
c    3
dtype: int64

In [42]:
obj1[[0,1,2]]

0    2
1    3
2    1
dtype: int64

In [43]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [44]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [46]:
data[["three","one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [47]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [48]:
data[data["three"]>5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [49]:
data[data<5] = 0

In [50]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [51]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [52]:
data.loc[["Colorado","Ohio"]]

          one  two  three  four
Colorado    0    5      6     7
Ohio        0    0      0     0

In [53]:
data.loc[["Colorado","New York"], ["one","three"]]

          one  three
Colorado    0      6
New York   12     14

In [54]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [55]:
data.iloc[[1,3],[0,2]]

          one  three
Colorado    0      6
New York   12     14

In [56]:
data.loc[:,"one"] = 1

In [57]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [58]:
data.iloc[2] = 5

In [59]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [60]:
data.loc[["Colorado", "New York"]] = 3

In [61]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [62]:
data.iloc[[1,3]] = 2

In [63]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    2    2      2     2
Utah        5    5      5     5
New York    2    2      2     2

In [64]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [65]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [66]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [67]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [68]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])

In [69]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [70]:
df1 = DataFrame({"A": [1,2]})

In [71]:
df1

   A
0  1
1  2

In [72]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))
df2.loc[1, "b"] = np.nan

In [73]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [74]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [75]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [76]:
1/df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [77]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [78]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [79]:
arr = np.arange(12.).reshape((3,4))

In [80]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [81]:
arr[0]

array([0., 1., 2., 3.])

In [82]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [83]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]

In [84]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [85]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [86]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [87]:
series3 = frame["d"]

In [88]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [89]:
frame.sub(series3, axis = "index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [ ]:
s