In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

In [4]:
obj = Series([4,7,5,3])

In [5]:
obj

0    4
1    7
2    5
3    3
dtype: int64

In [6]:
obj.array

<NumpyExtensionArray>
[4, 7, 5, 3]
Length: 4, dtype: int64

In [8]:
obj2 = Series([4,7,5,3], index = ["d", "b", "a", "c"])

In [9]:
obj2

d    4
b    7
a    5
c    3
dtype: int64

In [10]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
obj2["a"]

np.int64(5)

In [14]:
obj2 > 0

d    True
b    True
a    True
c    True
dtype: bool

In [15]:
sdata = {"Ohio" : 35000, "Texas" : 71000, "Oregon" : 16000, "Utah" : 5000}

In [16]:
obj3 = Series(sdata)

In [17]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [18]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [22]:
obj4 = Series(sdata, index = states)

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj4.notna()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
obj4.name = "population"

In [29]:
obj4.index.name = "state"

In [30]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
obj

0    4
1    7
2    5
3    3
dtype: int64

In [32]:
obj[2] = -5

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [5]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [6]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [7]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [9]:
DataFrame(data, columns=["year","state","pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [10]:
frame.loc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [11]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

NameError: name 'frame3' is not defined

In [12]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [13]:
frame2 = DataFrame(populations)

In [14]:
frame2

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [15]:
frame3.T

NameError: name 'frame3' is not defined

In [16]:
frame2.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [17]:
DataFrame(populations, index=[2001,2002,2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [18]:
frame1.to_numpy()

NameError: name 'frame1' is not defined

In [19]:
frame.to_numpy()

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

In [20]:
frame2.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [22]:
obj = Series(np.arange(3), index=["a", "b", "c"])

In [23]:
index = obj.index

In [24]:
index

Index(['a', 'b', 'c'], dtype='object')

In [25]:
index[1:]

Index(['b', 'c'], dtype='object')

In [26]:
labels = pd.Index(np.arange(3))

In [27]:
labels

Index([0, 1, 2], dtype='int64')

In [29]:
obj2 = Series([1.5, -2.5, 0], index = labels)

In [30]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [31]:
obj.index is labels

False

In [32]:
obj2.index is labels

True

In [33]:
frame3

NameError: name 'frame3' is not defined

In [34]:
frame2

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [37]:
frame2.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [36]:
frame2.columns.name = "state"

In [38]:
"Ohio" in frame2.columns

True

In [39]:
frame2.index

Index([2000, 2001, 2002], dtype='int64')

In [42]:
pd.Index(["foo","foo","bar","bar"])

TypeError: 'list' object is not callable

In [43]:
list = np.arange(3)

In [44]:
list

array([0, 1, 2])

In [45]:
pd.Index([0,1,2])

TypeError: 'list' object is not callable

In [46]:
pd.Index(np.array([0,1,2]))

TypeError: 'list' object is not callable

In [48]:
np.array([0,1,2])

array([0, 1, 2])

In [49]:
idx = pd.Index(list)

TypeError: 'list' object is not callable

In [50]:
del list

In [51]:
arr = np.arange(3)

In [52]:
arr

array([0, 1, 2])

In [53]:
idx = pd.Index(arr)

TypeError: 'list' object is not callable

In [54]:
print(type(list))

<class 'type'>

In [60]:
print(type(pd.Index)) 
# 만약 결과가 <class 'list'> 라면, pd.Index가 변수로 오염된 것입니다.
# 정상이라면 <class 'type'> (또는 pandas 내부 클래스명)이 떠야 합니다.

<class 'list'>

In [5]:
labels = pd.Index(["foo", "foo", "bar", "bar"])

In [6]:
labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [11]:
labels = labels.append(labels2)

In [8]:
labels2 = pd.Index(["tic", "tic"])

In [10]:
labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [12]:
labels

Index(['foo', 'foo', 'bar', 'bar', 'tic', 'tic'], dtype='object')

In [13]:
labels.difference(labels2)

Index(['bar', 'foo'], dtype='object')

In [14]:
labels.unique()

Index(['foo', 'bar', 'tic'], dtype='object')